version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "127.0.0.1:4510-4559:4510-4559"  # external service port range
      - "127.0.0.1:6566:4566"            # LocalStack Edge Proxy
    environment:
      - DEBUG=${DEBUG-}
      - DATA_DIR=${DATA_DIR-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_SERVICES=s3
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"




# Example command list bucket
# AWS_ACCESS_KEY_ID=some_access_key_id AWS_SECRET_ACCESS_KEY=some_secret_access_key  aws --endpoint-url=http://localhost:6566 --region=eu-central-1 s3  ls

# Example command create bucket
# AWS_ACCESS_KEY_ID=some_access_key_id AWS_SECRET_ACCESS_KEY=some_secret_access_key aws --endpoint-url=http://localhost:6566 --region=eu-central-1 s3  mb octopus-doganbros-storage