export const baseMeetingConfig = {
  disableAudioLevels: false,
  audioLevelsInterval: 200,
  enableNoAudioDetection: true,
  enableNoisyMicDetection: true,
  startAudioOnly: false,
  startAudioMuted: 10,
  startWithAudioMuted: false,
  startVideoMuted: 10,
  startWithVideoMuted: false,
  startScreenSharing: false,
  // fileRecordingsEnabled: false,
  // liveStreamingEnabled: false,
  disableResponsiveTiles: false,
  hideLobbyButton: false,
  requireDisplayName: true,
  defaultLanguage: 'en',
  disableProfile: false,
  transcribingEnabled: false,
  autoCaptionOnRecord: false,
  disableShortcuts: false,
  disableTileView: false,
  toolbarButtons: [
    { label: 'Microphone', setting: 'microphone' },
    { label: 'Camera', setting: 'camera' },
    { label: 'Closed captions', setting: 'closedcaptions' },
    { label: 'Desktop', setting: 'desktop' },
    { label: 'Embed meeting', setting: 'embedmeeting' },
    { label: 'Fullscreen', setting: 'fullscreen' },
    { label: 'Device selection', setting: 'fodeviceselection' },
    { label: 'Hangup', setting: 'hangup' },
    { label: 'Profile', setting: 'profile' },
    { label: 'Chat', setting: 'chat' },
    { label: 'Recording', setting: 'recording' },
    { label: 'Live streaming', setting: 'livestreaming' },
    { label: 'Etherpad', setting: 'etherpad' },
    { label: 'Shared video', setting: 'sharedvideo' },
    { label: 'Share audio', setting: 'shareaudio' },
    { label: 'Settings', setting: 'settings' },
    { label: 'Raise hand', setting: 'raisehand' },
    { label: 'Video quality', setting: 'videoquality' },
    { label: 'Filmstrip', setting: 'filmstrip' },
    { label: 'Feedback', setting: 'feedback' },
    { label: 'Stats', setting: 'stats' },
    { label: 'Shotcuts', setting: 'shortcuts' },
    { label: 'Tileview', setting: 'tileview' },
    { label: 'Select background', setting: 'select-background' },
    { label: 'Download', setting: 'download' },
    { label: 'Help', setting: 'help' },
    { label: 'Mute everyone', setting: 'mute-everyone' },
    { label: 'Mute video everyone', setting: 'mute-video-everyone' },
    { label: 'Security', setting: 'security' },
  ],
  disableRecordAudioNotification: false,
  disableJoinLeaveSounds: false,
  disableRemoteMute: true,
  hideConferenceSubject: false,
  hideConferenceTimer: true,
  hideParticipantsStats: true,
};
