export const MAIL_VERIFICATION_TYPE = 'MAIL_VERIFICATION_TYPE';
export const PASSWORD_VERIFICATION_TYPE = 'PASSWORD_VERIFICATION_TYPE';
export const OCTOPUS_CLIENT_AUTH_TYPE = 'OCTOPUS_CLIENT_AUTH_TYPE';
export const OCTOPUS_USER_AUTH_TYPE = 'OCTOPUS_USER_AUTH_TYPE';
