export const MAIL_VERIFICATION_TYPE = 'MAIL_VERIFICATION_TYPE';
export const PASSWORD_VERIFICATION_TYPE = 'PASSWORD_VERIFICATION_TYPE';
export const PURPIE_CLIENT_AUTH_TYPE = 'PURPIE_CLIENT_AUTH_TYPE';
export const PURPIE_USER_AUTH_TYPE = 'PURPIE_USER_AUTH_TYPE';
