export const ZONE_SUGGESTIONS_REQUESTED = 'ZONE_SUGGESTIONS_REQUESTED';
export const ZONE_SUGGESTIONS_SUCCESS = 'ZONE_SUGGESTIONS_SUCCESS';
export const ZONE_SUGGESTIONS_FAILED = 'ZONE_SUGGESTIONS_FAILED';
export const CHANNEL_SUGGESTIONS_REQUESTED = 'CHANNEL_SUGGESTIONS_REQUESTED';
export const CHANNEL_SUGGESTIONS_SUCCESS = 'CHANNEL_SUGGESTIONS_SUCCESS';
export const CHANNEL_SUGGESTIONS_FAILED = 'CHANNEL_SUGGESTIONS_FAILED';
export const CONTACT_SUGGESTIONS_REQUESTED = 'CONTACT_SUGGESTIONS_REQUESTED';
export const CONTACT_SUGGESTIONS_SUCCESS = 'CONTACT_SUGGESTIONS_SUCCESS';
export const CONTACT_SUGGESTIONS_FAILED = 'CONTACT_SUGGESTIONS_FAILED';
export const LIST_INVITATION_REQUESTED = 'LIST_INVITATION_REQUESTED';
export const LIST_INVITATION_SUCCESS = 'LIST_INVITATION_SUCCESS';
export const LIST_INVITATION_FAILED = 'LIST_INVITATION_FAILED';
export const GET_INVITATION_RESPONSE_REQUESTED =
  'GET_INVITATION_RESPONSE_REQUESTED';
export const GET_INVITATION_RESPONSE_SUCCESS =
  'GET_INVITATION_RESPONSE_SUCCESS';
export const GET_INVITATION_RESPONSE_FAILED = 'GET_INVITATION_RESPONSE_FAILED';
export const CREATE_CONTACT_INVITATION_REQUESTED =
  'CREATE_CONTACT_INVITATION_REQUESTED';
export const CREATE_CONTACT_INVITATION_SUCCESS =
  'CREATE_CONTACT_INVITATION_SUCCESS';
export const CREATE_CONTACT_INVITATION_FAILED =
  'CREATE_CONTACT_INVITATION_FAILED';
