export const ZONE_SUGGESTIONS_REQUESTED = 'ZONE_SUGGESTIONS_REQUESTED';
export const ZONE_SUGGESTIONS_SUCCESS = 'ZONE_SUGGESTIONS_SUCCESS';
export const ZONE_SUGGESTIONS_FAILED = 'ZONE_SUGGESTIONS_FAILED';
export const CHANNEL_SUGGESTIONS_REQUESTED = 'CHANNEL_SUGGESTIONS_REQUESTED';
export const CHANNEL_SUGGESTIONS_SUCCESS = 'CHANNEL_SUGGESTIONS_SUCCESS';
export const CHANNEL_SUGGESTIONS_FAILED = 'CHANNEL_SUGGESTIONS_FAILED';
export const LIST_INVITATION_REQUESTED = 'LIST_INVITATION_REQUESTED';
export const LIST_INVITATION_SUCCESS = 'LIST_INVITATION_SUCCESS';
export const LIST_INVITATION_FAILED = 'LIST_INVITATION_FAILED';
export const GET_INVITATION_RESPONSE_REQUESTED =
  'GET_INVITATION_RESPONSE_REQUESTED';
export const GET_INVITATION_RESPONSE_SUCCESS =
  'GET_INVITATION_RESPONSE_SUCCESS';
export const GET_INVITATION_RESPONSE_FAILED = 'GET_INVITATION_RESPONSE_FAILED';
export const NOTIFICATION_REQUESTED = 'NOTIFICATION_REQUESTED';
export const NOTIFICATION_SUCCESS = 'NOTIFICATION_SUCCESS';
export const NOTIFICATION_FAILED = 'NOTIFICATION_FAILED';
export const NOTIFICATION_COUNT_REQUESTED = 'NOTIFICATION_COUNT_REQUESTED';
export const NOTIFICATION_COUNT_SUCCESS = 'NOTIFICATION_COUNT_SUCCESS';
export const NOTIFICATION_COUNT_FAILED = 'NOTIFICATION_COUNT_FAILED';
