export const API_KEY_SECRET_REQUESTED = 'API_KEY_SECRET_REQUESTED';
export const API_KEY_SECRET_SUCCESS = 'API_KEY_SECRET_SUCCESS';
export const API_KEY_SECRET_FAILED = 'API_KEY_SECRET_FAILED';

export const GENERATE_API_KEY_SECRET_REQUESTED =
  'GENERATE_API_KEY_SECRET_REQUESTED';
export const GENERATE_API_KEY_SECRET_SUCCESS =
  'GENERATE_API_KEY_SECRET_SUCCESS';
export const GENERATE_API_KEY_SECRET_FAILED = 'GENERATE_API_KEY_SECRET_FAILED';
