export const THIRD_PARTY_URL_REQUESTED = 'THIRD_PARTY_URL_REQUESTED';
export const THIRD_PARTY_URL_FAILED = 'THIRD_PARTY_URL_FAILED';
export const THIRD_PARTY_AUTH_WITH_CODE_REQUESTED =
  'THIRD_PARTY_AUTH_WITH_CODE_REQUESTED';
export const THIRD_PARTY_AUTH_WITH_CODE_SUCCESS =
  'THIRD_PARTY_AUTH_WITH_CODE_SUCCESS';
export const THIRD_PARTY_AUTH_WITH_CODE_FAILED =
  'THIRD_PARTY_AUTH_WITH_CODE_FAILED';
export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const USER_RETRIEVED_FAILED = 'USER_RETRIEVED_FAILED';
export const USER_RETRIEVED_SUCCESS = 'USER_RETRIEVED_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const REGISTER_REQUESTED = 'REGISTER_REQUESTED';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const FORGOT_PASSWORD_REQUESTED = 'FORGOT_PASSWORD_REQUESTED';
export const FORGOT_PASSWORD_SUCCESS = 'FORGET_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILED = 'FORGET_PASSWORD_FAILED';
export const RESET_PASSWORD_REQUESTED = 'RESET_PASSWORD_REQUESTED';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED';
