export const GET_USER_CHANNELS_REQUESTED = 'GET_USER_CHANNELS_REQUESTED';
export const GET_USER_CHANNELS_SUCCESS = 'GET_USER_CHANNELS_SUCCESS';
export const GET_USER_CHANNELS_FAILED = 'GET_USER_CHANNELS_FAILED';
export const JOIN_CHANNEL_REQUESTED = 'JOIN_CHANNEL_REQUESTED';
export const JOIN_CHANNEL_SUCCESS = 'JOIN_CHANNEL_SUCCESS';
export const JOIN_CHANNEL_FAILED = 'JOIN_CHANNEL_FAILED';
