export const SET_MATTERMOST_CURRENT_USER = 'SET_MATTERMOST_CURRENT_USER';
export const SET_MATTERMOST_WEBSOCKET_EVENT = 'SET_MATTERMOST_WEBSOCKET_EVENT';
export const SET_MATTERMOST_CHANNEL_INFO = 'SET_MATTERMOST_CHANNEL_INFO';
