export const SET_MATTERMOST_CURRENT_USER = 'SET_MATTERMOST_CURRENT_USER';
export const SET_MATTERMOST_WEBSOCKET_EVENT = 'SET_MATTERMOST_WEBSOCKET_EVENT';
export const SET_MATTERMOST_CURRENT_TEAM = 'SET_MATTERMOST_CURRENT_TEAM';
export const REMOVE_USER_FROM_CHANNEL = 'REMOVE_USER_FROM_CHANNEL';
export const SET_MATTERMOST_CHANNEL_INFO = 'SET_MATTERMOST_CHANNEL_INFO';
export const SET_MATTERMOST_USER_PROFILES = 'SET_MATTERMOST_USER_PROFILES';
