export const OPEN_CREATE_MEETING_LAYER = 'OPEN_CREATE_MEETING_LAYER';
export const CLOSE_CREATE_MEETING_LAYER = 'CLOSE_CREATE_MEETING_LAYER';
export const OPEN_UPDATE_MEETING_LAYER = 'OPEN_UPDATE_MEETING_LAYER';
export const CLOSE_UPDATE_MEETING_LAYER = 'CLOSE_UPDATE_MEETING_LAYER';
export const MEETING_CREATE_SUCCESS = 'MEETING_CREATE_SUCCESS';
export const MEETING_CREATE_FAILED = 'MEETING_CREATE_FAILED';
export const MEETING_CREATE_REQUESTED = 'MEETING_CREATE_REQUESTED';
export const GET_ALL_MEETINGS_SUCCESS = 'GET_ALL_MEETINGS_SUCCESS';
export const GET_ALL_MEETINGS_FAILED = 'GET_ALL_MEETINGS_FAILED';
export const GET_ALL_MEETINGS_REQUESTED = 'GET_ALL_MEETINGS_REQUESTED';
export const GET_ALL_MEETINGS_BY_USER_ZONE_ID_SUCCESS =
  'GET_ALL_MEETINGS_BY_USER_ZONE_ID_SUCCESS';
export const GET_ALL_MEETINGS_BY_USER_ZONE_ID_FAILED =
  'GET_ALL_MEETINGS_BY_USER_ZONE_ID_FAILED';
export const GET_ALL_MEETINGS_BY_USER_ZONE_ID_REQUESTED =
  'GET_ALL_MEETINGS_BY_USER_ZONE_ID_REQUESTED';
export const GET_MEETINGS_BY_ID_SUCCESS = 'GET_MEETINGS_BY_ID_SUCCESS';
export const GET_MEETINGS_BY_ID_FAILED = 'GET_MEETINGS_BY_ID_FAILED';
export const GET_MEETINGS_BY_ID_REQUESTED = 'GET_MEETINGS_BY_ID_REQUESTED';
export const DELETE_MEETINGS_BY_ID_SUCCESS = 'DELETE_MEETINGS_BY_ID_SUCCESS';
export const DELETE_MEETINGS_BY_ID_FAILED = 'DELETE_MEETINGS_BY_ID_FAILED';
export const DELETE_MEETINGS_BY_ID_REQUESTED =
  'DELETE_MEETINGS_BY_ID_REQUESTED';
export const UPDATE_MEETINGS_BY_ID_SUCCESS = 'UPDATE_MEETINGS_BY_ID_SUCCESS';
export const UPDATE_MEETINGS_BY_ID_FAILED = 'UPDATE_MEETINGS_BY_ID_FAILED';
export const UPDATE_MEETINGS_BY_ID_REQUESTED =
  'UPDATE_MEETINGS_BY_ID_REQUESTED';
export const GET_ALL_MEETINGS_BY_USER_ID_REQUESTED =
  'GET_ALL_MEETINGS_BY_USER_ID_REQUESTED';
export const GET_ALL_MEETINGS_BY_USER_ID_SUCCESS =
  'GET_ALL_MEETINGS_BY_USER_ID_SUCCESS';
export const GET_ALL_MEETINGS_BY_USER_ID_FAILED =
  'GET_ALL_MEETINGS_BY_USER_ID_FAILED';
