export const LIST_MEMBERSHIPS_REQUESTED = 'LIST_MEMBERSHIPS_REQUESTED';
export const LIST_MEMBERSHIPS_SUCCESS = 'LIST_MEMBERSHIPS_SUCCESS';
export const LIST_MEMBERSHIPS_FAILED = 'LIST_MEMBERSHIPS_FAILED';

export const GET_USER_MEMBERSHIP_REQUESTED = 'GET_USER_MEMBERSHIP_REQUESTED';
export const GET_USER_MEMBERSHIP_SUCCESS = 'GET_USER_MEMBERSHIP_SUCCESS';
export const GET_USER_MEMBERSHIP_FAILED = 'GET_USER_MEMBERSHIP_FAILED';
