export const VIDEO_CREATE_REQUESTED = 'VIDEO_CREATE_REQUESTED';
export const VIDEO_CREATE_SUCCESS = 'VIDEO_CREATE_SUCCESS';
export const VIDEO_CREATE_FAILED = 'VIDEO_CREATE_FAILED';
export const VIDEO_DETAIL_REQUESTED = 'VIDEO_DETAIL_REQUESTED';
export const VIDEO_DETAIL_SUCCESS = 'VIDEO_DETAIL_SUCCESS';
export const VIDEO_DETAIL_FAILED = 'VIDEO_DETAIL_FAILED';
