export const GET_USER_ZONES_REQUESTED = 'GET_USER_ZONES_REQUESTED';
export const GET_USER_ZONES_SUCCESS = 'GET_USER_ZONES_SUCCESS';
export const GET_USER_ZONES_FAILED = 'GET_USER_ZONES_FAILED';

export const OPEN_CREATE_ZONE_LAYER = 'OPEN_CREATE_ZONE_LAYER';
export const CLOSE_CREATE_ZONE_LAYER = 'CLOSE_CREATE_ZONE_LAYER';

export const CREATE_ZONE_REQUESTED = 'CREATE_ZONE_REQUESTED';
export const CREATE_ZONE_SUCCESS = 'CREATE_ZONE_SUCCESS';
export const CREATE_ZONE_FAILED = 'CREATE_ZONE_FAILED';

export const JOIN_ZONE_REQUESTED = 'JOIN_ZONE_REQUESTED';
export const JOIN_ZONE_SUCCESS = 'JOIN_ZONE_SUCCESS';
export const JOIN_ZONE_FAILED = 'JOIN_ZONE_FAILED';

export const UPDATE_ZONE_REQUESTED = 'UPDATE_ZONE_REQUESTED';
export const UPDATE_ZONE_SUCCESS = 'UPDATE_ZONE_SUCCESS';
export const UPDATE_ZONE_FAILED = 'UPDATE_ZONE_FAILED';

export const DELETE_USER_ZONE_REQUESTED = 'DELETE_USER_ZONE_REQUESTED';
export const DELETE_USER_ZONE_SUCCESS = 'DELETE_USER_ZONE_SUCCESS';
export const DELETE_USER_ZONE_FAILED = 'DELETE_USER_ZONE_FAILED';

export const DELETE_ZONE_REQUESTED = 'DELETE_ZONE_REQUESTED';
export const DELETE_ZONE_SUCCESS = 'DELETE_ZONE_SUCCESS';
export const DELETE_ZONE_FAILED = 'DELETE_ZONE_FAILED';

export const GET_USER_ZONE_BY_ID_REQUESTED = 'GET_USER_ZONE_BY_ID_REQUESTED';
export const GET_USER_ZONE_BY_ID_SUCCESS = 'GET_USER_ZONE_BY_ID_SUCCESS';
export const GET_USER_ZONE_BY_ID_FAILED = 'GET_USER_ZONE_BY_ID_FAILED';

export const GET_CURRENT_USER_ZONE_REQUESTED =
  'GET_CURRENT_USER_ZONE_REQUESTED';
export const GET_CURRENT_USER_ZONE_SUCCESS = 'GET_CURRENT_USER_ZONE_SUCCESS';
export const GET_CURRENT_USER_ZONE_FAILED = 'GET_CURRENT_USER_ZONE_FAILED';

export const INVITE_TO_ZONE_REQUESTED = 'INVITE_TO_ZONE_REQUESTED';
export const INVITE_TO_ZONE_SUCCESS = 'INVITE_TO_ZONE_SUCCESS';
export const INVITE_TO_ZONE_FAILED = 'INVITE_TO_ZONE_FAILED';

export const SET_CURRENT_USER_ZONE = 'SET_CURRENT_USER_ZONE';

export const SEARCH_ZONE_REQUESTED = 'SEARCH_ZONE_REQUESTED';
export const SEARCH_ZONE_SUCCESS = 'SEARCH_ZONE_SUCCESS';
export const SEARCH_ZONE_FAILED = 'SEARCH_ZONE_FAILED';

export const CHANGE_ZONE_PICTURE_FAILED = 'CHANGE_ZONE_PICTURE_FAILED';
export const CHANGE_ZONE_PICTURE_REQUESTED = 'CHANGE_ZONE_PICTURE_REQUESTED';
export const CHANGE_ZONE_PICTURE_SUCCESS = 'CHANGE_ZONE_PICTURE_SUCCESS';

export const CHANGE_ZONE_INFO_REQUESTED = 'CHANGE_ZONE_INFO_REQUEST';
export const CHANGE_ZONE_INFO_SUCCESS = 'CHANGE_ZONE_INFO_SUCCESS';
export const CHANGE_ZONE_INFO_FAILED = 'CHANGE_ZONE_INFO_FAILED';

export const CHANGE_ZONE_PERMISSIONS_REQUESTED =
  'CHANGE_ZONE_PERMISSIONS_REQUEST';
export const CHANGE_ZONE_PERMISSIONS_SUCCESS =
  'CHANGE_ZONE_PERMISSIONS_SUCCESS';
export const CHANGE_ZONE_PERMISSIONS_FAILED = 'CHANGE_ZONE_PERMISSIONS_FAILED';
