name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Change this if you're using a different version of Node.js

      - name: Install dependencies (Frontend)
        run: |
          yarn install

      - name: Build frontend
        run: |
          yarn build

      - name: Replace build folder
        run: |
          sudo rm -rf /var/www/purpie/build
          sudo cp -r ./build /var/www/purpie/

  deploy-backend:
    runs-on: self-hosted
    needs: deploy-frontend # Ensures frontend job runs before the backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Change this if you're using a different version of Node.js

      - name: Kill process running on port 8000 (if any)
        run: |
          if lsof -i:8000; then
            sudo fuser -k 8000/tcp
          else
            echo "No process running on port 8000"
          fi

      - name: Start backend server
        run: |
          nohup yarn server:start &

      - name: Verify the backend server is running
        run: |
          curl --silent --fail http://localhost:8000 || exit 1

      - name: Reload Nginx
        run: |
          sudo systemctl reload nginx
