import { PostType } from '../../../store/types/post.types';

const post1 = {
  id: 26,
  createdOn: new Date('2022-02-09T18:08:38.702Z'),
  updatedOn: null,
  title: 'Lemon cocktail closeup',
  description: 'Close up shot of a lemon cocktail',
  slug: 'b987019d-771c-41a7-bd8b-9cbec637cfe2',
  conferenceStartDate: null,
  conferenceEndDate: null,
  timeZone: null,
  type: PostType.video,
  createdById: 1,
  channelId: 5,
  streaming: false,
  public: false,
  private: false,
  liveStream: false,
  record: false,
  videoName: 'b987019d-771c-41a7-bd8b-9cbec637cfe2.mp4',
  userContactExclusive: false,
  postReactionId: 25,
  allowDislike: true,
  allowReaction: true,
  allowComment: true,
  liked: false,
  saved: false,
  disliked: false,
  createdBy: {
    id: 1,
    firstName: 'Fecri Kaan',
    lastName: 'Ulubey',
    email: 'f.kaan93@gmail.com',
    userName: 'f.kaan93',
  },
  postReaction: {
    likesCount: 0,
    dislikesCount: 0,
    commentsCount: 1,
    viewsCount: 5,
    liveStreamViewersCount: 0,
  },
  channel: {
    id: 5,
    name: 'Jazz',
    topic: 'jazz',
    description: 'Jazz',
    public: true,
    zone: {
      id: 3,
      name: 'Everything Music',
      subdomain: 'everything-music',
      public: true,
    },
  },
};
const post2 = {
  id: 25,
  createdOn: new Date('2022-02-09T18:08:38.702Z'),
  updatedOn: null,
  title: 'Bird on a tree',
  description: 'Wild bird nested on a tree',
  slug: '6f38f04c-7a57-496b-ac00-1ed2f3e20ca2',
  conferenceStartDate: null,
  conferenceEndDate: null,
  timeZone: null,
  type: PostType.video,
  createdById: 1,
  channelId: 5,
  streaming: false,
  public: false,
  private: false,
  liveStream: false,
  record: false,
  videoName: '6f38f04c-7a57-496b-ac00-1ed2f3e20ca2.mp4',
  userContactExclusive: false,
  postReactionId: 25,
  allowDislike: true,
  allowReaction: true,
  allowComment: true,
  liked: false,
  saved: false,
  disliked: false,
  createdBy: {
    id: 1,
    firstName: 'Fecri Kaan',
    lastName: 'Ulubey',
    email: 'f.kaan93@gmail.com',
    userName: 'f.kaan93',
  },
  postReaction: {
    likesCount: 0,
    dislikesCount: 0,
    commentsCount: 1,
    viewsCount: 5,
    liveStreamViewersCount: 0,
  },
  channel: {
    id: 5,
    name: 'Jazz',
    topic: 'jazz',
    description: 'Jazz',
    public: true,
    zone: {
      id: 3,
      name: 'Everything Music',
      subdomain: 'everything-music',
      public: true,
    },
  },
};
export const userData = {
  featuredPost: post1,
  friends: [
    {
      id: 1,
      firstName: 'John',
      lastName: 'Doe',
      userName: 'john-doe',
    },
    {
      id: 2,
      firstName: 'Jane',
      lastName: 'Doe',
      userName: 'john-doe',
    },
    {
      id: 3,
      firstName: 'Jill',
      lastName: 'Doe',
      userName: 'jill-doe',
    },
    {
      id: 4,
      firstName: 'Jake',
      lastName: 'Doe',
      userName: 'jake-doe',
    },
  ],
  joinedChannels: [
    {
      channel_id: 2,
      channel_createdOn: '2021-10-20T15:37:59.574Z',
      channel_name: 'Parrots',
      channel_topic: 'parrots',
      channel_description: 'Parrots',
      channel_public: true,
      zone_id: 1,
      zone_name: 'Pets & Animals',
      zone_subdomain: 'pets-and-animals',
      category_id: 4004,
      category_name: 'Bird',
      channel_membersCount: '1',
    },
    {
      channel_id: 1,
      channel_createdOn: '2021-10-20T15:37:15.545Z',
      channel_name: 'Dogs',
      channel_topic: 'dogs',
      channel_description: 'Dogs',
      channel_public: true,
      zone_id: 1,
      zone_name: 'Pets & Animals',
      zone_subdomain: 'pets-and-animals',
      category_id: 4001,
      category_name: 'Dog',
      channel_membersCount: '1',
    },
  ],
  joinedZones: [
    {
      zone_id: 4,
      zone_createdOn: '2021-10-21T01:08:00.171Z',
      zone_name: 'Test',
      zone_subdomain: 'test',
      zone_description: 'Test',
      zone_public: true,
      category_id: 5,
      category_name: 'Sports',
      zone_channelCount: '0',
      zone_membersCount: '1',
    },
  ],
  sharedLists: [
    { id: 1, name: 'Some Video List', posts: [post1, post2, post1] },
    { id: 1, name: 'Test List', posts: [post1, post2] },
  ],
};
